# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths:
      - 'docs/**'
      - 'utils/**'
      - '.github/workflows/build-pvldb-analysis.yaml'
      - 'renv.lock'
      - 'requirements.txt'

name: build-pvldb-analysis

jobs:
  build-pvldb-analysis:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python requirements
        run: pip install -r requirements.txt

      - name: Retrieve data via Crossref
        run: utils/crossref

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Build site
        run: utils/render

      - name: Create .nojekyll file
        run: touch public/.nojekyll

      - name: Retrieve file LICENSE
        run: curl https://creativecommons.org/licenses/by/4.0/legalcode.txt > public/LICENSE

      - name: Retrieve file data/LICENSE
        run: curl https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt > public/data/LICENSE

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: true
          branch: gh-pages
          folder: public
